### ISSUE TITLE
cam issue on mac pro

### ISSUE THREAD

**Issue by cpgmedialab** [RELNO/CityScope_Scanner_Python#4]
```
2018-11-13 12:01:59.685 Python[37304:1881395] *** AVCaptureSession warning: Session received the following error while decompressing video: Error Domain=NSOSStatusErrorDomain Code=-12903 "(null)". Make sure that the formats of all video outputs are properly configured.
Process Process-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/cityscience/Documents/GitHub/CityScope_Scanner_Python/modules.py", line 171, in scanner_function
    THIS_FRAME, KEY_STONE_DATA, (video_resolution_x, video_resolution_y))
cv2.error: OpenCV(3.4.2) /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/imgwarp.cpp:2902: error: (-215:Assertion failed) _src.total() > 0 in function 'warpPerspective'
```

**Comment by RELNO** [comment]
https://github.com/RELNO/CityScope_Scanner_Python/commit/c3044755ad9a80031002abb1cf2ce2a8ddf75fc8 moved webcam handeling outside of multiproccess world for now. this is a bypass, not a full solution but the two other processes are still ok.
